name: crazycode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  crazycode:
    if: |
      contains(github.event.comment.body, ' /crazy') ||
      startsWith(github.event.comment.body, '/crazy') ||
      contains(github.event.comment.body, ' /crazycode') ||
      startsWith(github.event.comment.body, '/crazycode')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run crazycode
        uses: ./github
        env:
          CRAZYCODE_API_KEY: ${{ secrets.CRAZYCODE_API_KEY }}
          CRAZYCODE_PERMISSION: '{"bash": "deny"}'
        with:
          model: crazycode/claude-opus-4-5
